// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBimokCpBc7F8KI1sbFSKJvGq8jCEOjOo',
    appId: '1:553589299030:web:9ecc1fb113d2eae4d7a8f7',
    messagingSenderId: '553589299030',
    projectId: 'todolist-1c33e',
    authDomain: 'todolist-1c33e.firebaseapp.com',
    databaseURL: 'https://todolist-1c33e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-1c33e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMRKg6c8Q6XO_hOTS-y3c102o5w895wRg',
    appId: '1:553589299030:android:24e49ada533459b2d7a8f7',
    messagingSenderId: '553589299030',
    projectId: 'todolist-1c33e',
    databaseURL: 'https://todolist-1c33e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-1c33e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmYAJZno24T9A174E8F39oiNOQX1MNyR8',
    appId: '1:553589299030:ios:71360e3d939e5b81d7a8f7',
    messagingSenderId: '553589299030',
    projectId: 'todolist-1c33e',
    databaseURL: 'https://todolist-1c33e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-1c33e.appspot.com',
    iosClientId: '553589299030-r8qmp1m6ctgiv7h3frssbriu8bh8mf42.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmYAJZno24T9A174E8F39oiNOQX1MNyR8',
    appId: '1:553589299030:ios:71360e3d939e5b81d7a8f7',
    messagingSenderId: '553589299030',
    projectId: 'todolist-1c33e',
    databaseURL: 'https://todolist-1c33e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todolist-1c33e.appspot.com',
    iosClientId: '553589299030-r8qmp1m6ctgiv7h3frssbriu8bh8mf42.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );
}
